<?php

  function clocktower_player_menu() {
    $items['player/%/%'] = array(
      'title' => 'Clocktower Player',
      'description' => 'Clocktower jPlayer',
      'page callback' => 'clocktower_player_page',
      'page arguments' => array(2, 3),
      'access arguments' => array('access content'),
    );
    return $items;
  }

  /**
   * Implements hook_theme().
   */
  function clocktower_player_theme($existing, $type, $theme, $path) {
    return array(
      'clocktower_player' => array(
        'template' => 'templates/clocktower-player-page',
      ),
    );
  }

  function clocktower_player_page($node, $shuffle) {
    drupal_add_js(drupal_get_path('module', 'clocktower_player') . '/js/clocktower-player.js');
    drupal_add_js('sites/all/libraries/jplayer/jquery.jplayer.min.js');
    drupal_add_js('sites/all/libraries/jplayer/jquery.jplayer.swf');
    drupal_add_css(drupal_get_path('module', 'clocktower_player') . '/css/jplayer.blue.monday.css');
    $page_elements = array(
      'node' => $node,
      'shuffle' => $shuffle,
    );
    return theme('clocktower_player', $page_elements);
  }
?>